"""Add column for last_modified_date

Revision ID: 176ef492295b
Revises: 528229141ae0
Create Date: 2025-12-24 21:14:46.775718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '176ef492295b'
down_revision: Union[str, Sequence[str], None] = '528229141ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_import', sa.Column('last_modified_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_import', 'last_modified_date')
    # ### end Alembic commands ###
