"""Create table to store import status

Revision ID: 18b01f93792c
Revises: 641636eb91c7
Create Date: 2025-12-24 19:46:00.725862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18b01f93792c'
down_revision: Union[str, Sequence[str], None] = '641636eb91c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_import',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('users_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cards_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transactions_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_import')
    # ### end Alembic commands ###
