"""Create 'Users' table

Revision ID: 19f9c228fc9d
Revises: bd18483aef24
Create Date: 2025-11-27 22:13:25.478535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '19f9c228fc9d'
down_revision: Union[str, Sequence[str], None] = 'bd18483aef24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_age', sa.SmallInteger(), nullable=True),
    sa.Column('retirement_age', sa.SmallInteger(), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('birth_month', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('per_capita_income', sa.Integer(), nullable=False),
    sa.Column('yearly_income', sa.Integer(), nullable=False),
    sa.Column('total_debt', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.BigInteger(), nullable=True),
    sa.Column('num_credit_cards', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cards', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cards', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('users')
    # ### end Alembic commands ###
