"""initial migration

Revision ID: 3c64db254d87
Revises: 
Create Date: 2025-11-27 07:10:43.760386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c64db254d87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('card_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires', sa.Date(), nullable=False),
    sa.Column('cvv', sa.SmallInteger(), nullable=True),
    sa.Column('has_chip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_cards_issued', sa.SmallInteger(), nullable=True),
    sa.Column('credit_limit', sa.BigInteger(), nullable=True),
    sa.Column('acct_open_date', sa.Date(), nullable=False),
    sa.Column('year_pin_last_changed', sa.SmallInteger(), nullable=True),
    sa.Column('card_on_dark_web', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
