"""Allow merchant_state and zip fields/columns to support None

Revision ID: 641636eb91c7
Revises: 9eb9d6ca8dfa
Create Date: 2025-12-07 14:56:15.308523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '641636eb91c7'
down_revision: Union[str, Sequence[str], None] = '9eb9d6ca8dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'merchant_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'merchant_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'merchant_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'merchant_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
