"""Add trigger to record changes made in tables to audit log table

Revision ID: 90f596a58529
Revises: 78b13dda84b0
Create Date: 2025-12-27 19:09:51.347122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90f596a58529'
down_revision: Union[str, Sequence[str], None] = '78b13dda84b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
