"""Set none fields option for online based transactions without zip, mcc. Modify error fields to support none for transactions without errors.

Revision ID: 9d222f8b1b8f
Revises: 7c894cadbd14
Create Date: 2025-11-29 16:56:48.706600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d222f8b1b8f'
down_revision: Union[str, Sequence[str], None] = '7c894cadbd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'zip',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'mcc',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'errors',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'errors',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'mcc',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'zip',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
