"""Allow source field/column to support None

Revision ID: 9eb9d6ca8dfa
Revises: a0d3a42e7d9c
Create Date: 2025-12-07 13:39:17.108797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9eb9d6ca8dfa'
down_revision: Union[str, Sequence[str], None] = 'a0d3a42e7d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cards', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
