"""Add trigger to record changes made in tables to audit log table

Revision ID: b0193ea8cd4c
Revises: 90f596a58529
Create Date: 2025-12-28 07:29:48.949164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'b0193ea8cd4c'
down_revision: Union[str, Sequence[str], None] = '90f596a58529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_log_changes = PGFunction(
        schema="public",
        signature="log_changes()",
        definition="RETURNS TRIGGER AS $$\n    BEGIN\n        IF TG_OP = 'UPDATE' THEN\n            -- Only log if something actually changed\n            IF OLD IS DISTINCT FROM NEW THEN\n                INSERT INTO audit_log (table_name, operation, old_data, new_data, changed_at) \n                VALUES (TG_TABLE_NAME, TG_OP, row_to_json(OLD), row_to_json(NEW), NOW());\n            END IF;\n        ELSIF TG_OP = 'INSERT' THEN\n            INSERT INTO audit_log (table_name, operation, old_data, new_data, changed_at) \n            VALUES (TG_TABLE_NAME, TG_OP, NULL, row_to_json(NEW), NOW());\n        ELSIF TG_OP = 'DELETE' THEN\n            INSERT INTO audit_log (table_name, operation, old_data, new_data, changed_at) \n            VALUES (TG_TABLE_NAME, TG_OP, row_to_json(OLD), NULL, NOW());\n        END IF;\n        \n        RETURN COALESCE(NEW, OLD);\n    END;\n    $$ LANGUAGE plpgsql"
    )
    op.create_entity(public_log_changes)

    public_cards_audit_cards_trigger = PGTrigger(
        schema="public",
        signature="audit_cards_trigger",
        on_entity="public.cards",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE OR DELETE ON cards\n    FOR EACH ROW EXECUTE FUNCTION log_changes()'
    )
    op.create_entity(public_cards_audit_cards_trigger)

    public_transactions_audit_transactions_trigger = PGTrigger(
        schema="public",
        signature="audit_transactions_trigger",
        on_entity="public.transactions",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE OR DELETE ON transactions\n    FOR EACH ROW EXECUTE FUNCTION log_changes()'
    )
    op.create_entity(public_transactions_audit_transactions_trigger)

    public_users_audit_users_trigger = PGTrigger(
        schema="public",
        signature="audit_users_trigger",
        on_entity="public.users",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE OR DELETE ON users\n    FOR EACH ROW EXECUTE FUNCTION log_changes()'
    )
    op.create_entity(public_users_audit_users_trigger)

    public_data_import_audit_data_import_trigger = PGTrigger(
        schema="public",
        signature="audit_data_import_trigger",
        on_entity="public.data_import",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE OR DELETE ON data_import\n    FOR EACH ROW EXECUTE FUNCTION log_changes()'
    )
    op.create_entity(public_data_import_audit_data_import_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_data_import_audit_data_import_trigger = PGTrigger(
        schema="public",
        signature="audit_data_import_trigger",
        on_entity="public.data_import",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE OR DELETE ON data_import\n    FOR EACH ROW EXECUTE FUNCTION log_changes()'
    )
    op.drop_entity(public_data_import_audit_data_import_trigger)

    public_users_audit_users_trigger = PGTrigger(
        schema="public",
        signature="audit_users_trigger",
        on_entity="public.users",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE OR DELETE ON users\n    FOR EACH ROW EXECUTE FUNCTION log_changes()'
    )
    op.drop_entity(public_users_audit_users_trigger)

    public_transactions_audit_transactions_trigger = PGTrigger(
        schema="public",
        signature="audit_transactions_trigger",
        on_entity="public.transactions",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE OR DELETE ON transactions\n    FOR EACH ROW EXECUTE FUNCTION log_changes()'
    )
    op.drop_entity(public_transactions_audit_transactions_trigger)

    public_cards_audit_cards_trigger = PGTrigger(
        schema="public",
        signature="audit_cards_trigger",
        on_entity="public.cards",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE OR DELETE ON cards\n    FOR EACH ROW EXECUTE FUNCTION log_changes()'
    )
    op.drop_entity(public_cards_audit_cards_trigger)

    public_log_changes = PGFunction(
        schema="public",
        signature="log_changes()",
        definition="RETURNS TRIGGER AS $$\n    BEGIN\n        IF TG_OP = 'UPDATE' THEN\n            -- Only log if something actually changed\n            IF OLD IS DISTINCT FROM NEW THEN\n                INSERT INTO audit_log (table_name, operation, old_data, new_data, changed_at) \n                VALUES (TG_TABLE_NAME, TG_OP, row_to_json(OLD), row_to_json(NEW), NOW());\n            END IF;\n        ELSIF TG_OP = 'INSERT' THEN\n            INSERT INTO audit_log (table_name, operation, old_data, new_data, changed_at) \n            VALUES (TG_TABLE_NAME, TG_OP, NULL, row_to_json(NEW), NOW());\n        ELSIF TG_OP = 'DELETE' THEN\n            INSERT INTO audit_log (table_name, operation, old_data, new_data, changed_at) \n            VALUES (TG_TABLE_NAME, TG_OP, row_to_json(OLD), NULL, NOW());\n        END IF;\n        \n        RETURN COALESCE(NEW, OLD);\n    END;\n    $$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_log_changes)

    # ### end Alembic commands ###
