"""Create 'Transactions' table

Revision ID: bd18483aef24
Revises: 3c64db254d87
Create Date: 2025-11-27 21:32:43.877874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd18483aef24'
down_revision: Union[str, Sequence[str], None] = '3c64db254d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.SmallInteger(), nullable=True),
    sa.Column('card_id', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('use_chip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
