"""Add column for source in cards, transactions, users tables

Revision ID: c52cd89e63f8
Revises: 9d222f8b1b8f
Create Date: 2025-11-29 20:17:31.598536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c52cd89e63f8'
down_revision: Union[str, Sequence[str], None] = '9d222f8b1b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('transactions', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'source')
    op.drop_column('transactions', 'source')
    op.drop_column('cards', 'source')
    # ### end Alembic commands ###
