"""Set id's for tables to int

Revision ID: e5ca912013e2
Revises: 19f9c228fc9d
Create Date: 2025-11-27 22:29:51.703702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5ca912013e2'
down_revision: Union[str, Sequence[str], None] = '19f9c228fc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('card_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires', sa.Date(), nullable=False),
    sa.Column('cvv', sa.SmallInteger(), nullable=True),
    sa.Column('has_chip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_cards_issued', sa.SmallInteger(), nullable=True),
    sa.Column('credit_limit', sa.BigInteger(), nullable=True),
    sa.Column('acct_open_date', sa.Date(), nullable=False),
    sa.Column('year_pin_last_changed', sa.SmallInteger(), nullable=True),
    sa.Column('card_on_dark_web', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.SmallInteger(), nullable=True),
    sa.Column('card_id', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('use_chip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_age', sa.SmallInteger(), nullable=True),
    sa.Column('retirement_age', sa.SmallInteger(), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('birth_month', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('per_capita_income', sa.Integer(), nullable=False),
    sa.Column('yearly_income', sa.Integer(), nullable=False),
    sa.Column('total_debt', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.BigInteger(), nullable=True),
    sa.Column('num_credit_cards', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('cards')
    # ### end Alembic commands ###
